apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
  - image: gcr.io/engineering-devops/sk-amster
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
    - name: "{{.HELM_PREFIX}}sk-amster"
      chartPath: ../../helm/amster
      values:
        image: gcr.io/engineering-devops/sk-amster
      valuesFiles:
      - ../helm-common.yaml
    