apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: gcr.io/engineering-devops/sk-am
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
    - name: "{{ .HELM_PREFIX }}sk-am"
      chartPath: ../../helm/am
      valuesFiles:
      - ../helm-common.yaml
      values:
        image: gcr.io/engineering-devops/sk-am
      setValues:
        devMode: "false"
profiles:
# This profile deploys AM and amster to prep the idrepo. It disables File Based Config (FBC)
- name: prime
  deploy:
     helm:
      flags:
        install: ['-f', '../helm-common.yaml']
      releases:
      - name: "{{.HELM_PREFIX}}sk-am"
        chartPath: ../../helm/am
        values:
          image: gcr.io/engineering-devops/sk-am
        setValues:
          devMode: "false"
          catalinaOpts: "-server"
      - name: "{{.HELM_PREFIX}}sk-amster"
        chartPath: ../../helm/amster
        values:
          image: gcr.io/engineering-devops/sk-amster