social:
  facebook:
    id: "FakeID"
    secret: "FakeSecret"

openam:
  config:
    strategy: files

configstore:
  djInstance: configstore
  djPersistence: false
  opendjJavaArgs: "-Xmx400m"
  resources:
    limits:
      memory: 600Mi
    requests:
      memory: 400Mi
  image:
    repository: forgerock-docker-internal.bintray.io/ds

images:
  amster: forgerock-docker-public.bintray.io/forgerock/sample-fr-platform/amster:latest
  idm: forgerock-docker-public.bintray.io/forgerock/sample-fr-platform/idm:latest
  pg: forgerock-docker-public.bintray.io/forgerock/sample-fr-platform/pg:latest
  rs: forgerock-docker-public.bintray.io/forgerock/sample-fr-platform/rs:latest
